import type { FocusDef, FocusId } from '../core/types';

/**
 * National focus trees, HOI4-style: a branching set of multi-turn national
 * projects, each gated on its prerequisites and granting a real effect on
 * completion (stat boosts, an unlocked tech, a new tag, a relation swing, a
 * formed treaty). Authored for four flagship countries, one per the most
 * thematically fitting scenario — the same "not every country, but a real
 * one where it matters" scoping already used for legislature subgames and
 * province-level map geometry. Registered per-scenario via
 * ScenarioDefinition.focusTreeCountryIds (see worldFactory.ts) because a
 * CountryId's tree is specific to one era's tech/relations context.
 *
 * Coordinates (x, y) lay the tree out on a grid for the UI renderer: y is
 * depth from the root, x is the branch column. Capstone focuses converge
 * multiple branches back onto one prerequisite list.
 */
const registry: FocusDef[] = [
  // ============ Athens, 431 BCE — "Athenian Ascendancy" ============
  {
    id: 'ath-root',
    countryId: 'ATH',
    name: 'Strengthen the Delian League',
    description: 'Reaffirm Athenian leadership over the alliance of Aegean city-states.',
    prerequisiteIds: [],
    durationTurns: 3,
    x: 0,
    y: 0,
    effect: { stabilityDelta: 5, opinionDelta: 5 },
  },
  {
    id: 'ath-navy-1',
    countryId: 'ATH',
    name: 'Expand the Trireme Fleet',
    description: 'Fund a larger fleet of triremes to secure the sea lanes.',
    prerequisiteIds: ['ath-root'],
    durationTurns: 4,
    x: -1,
    y: 1,
    effect: { unlockTechId: 'trireme_design', militaryBonusDelta: 15 },
  },
  {
    id: 'ath-navy-2',
    countryId: 'ATH',
    name: 'Fortify Piraeus',
    description: "Strengthen the walls and defenses of Athens's port.",
    prerequisiteIds: ['ath-navy-1'],
    durationTurns: 4,
    x: -1,
    y: 2,
    effect: { stabilityDelta: 8, militaryBonusDelta: 10 },
  },
  {
    id: 'ath-econ-1',
    countryId: 'ATH',
    name: 'Grain Trade with the Black Sea',
    description: 'Formalize grain-trade routes to feed the growing city.',
    prerequisiteIds: ['ath-root'],
    durationTurns: 4,
    x: 1,
    y: 1,
    effect: { unlockTechId: 'maritime_trade_networks', growthBonusDelta: 0.01 },
  },
  {
    id: 'ath-econ-2',
    countryId: 'ATH',
    name: 'Silver Mines of Laurion',
    description: 'Expand state mining operations to fund the treasury.',
    prerequisiteIds: ['ath-econ-1'],
    durationTurns: 4,
    x: 1,
    y: 2,
    effect: { debtDelta: -15, growthBonusDelta: 0.008 },
  },
  {
    id: 'ath-pol-1',
    countryId: 'ATH',
    name: 'Expand Democratic Participation',
    description: "Broaden citizens' role in the Assembly.",
    prerequisiteIds: ['ath-root'],
    durationTurns: 3,
    x: 0,
    y: 1,
    effect: { unlockTechId: 'democratic_reform', stabilityDelta: 10 },
  },
  {
    id: 'ath-golden-age',
    countryId: 'ATH',
    name: 'The Athenian Golden Age',
    description: 'Bring naval, economic, and political strength together into a true golden age.',
    prerequisiteIds: ['ath-navy-2', 'ath-econ-2', 'ath-pol-1'],
    durationTurns: 5,
    x: 0,
    y: 3,
    effect: { stabilityDelta: 15, opinionDelta: 15, growthBonusDelta: 0.01 },
  },

  // ============ United States, 1836 — "Manifest Destiny" ============
  {
    id: 'usa-root',
    countryId: 'USA',
    name: 'Strengthen the Union',
    description: 'Shore up federal authority and national confidence.',
    prerequisiteIds: [],
    durationTurns: 3,
    x: 0,
    y: 0,
    effect: { stabilityDelta: 5, opinionDelta: 5 },
  },
  {
    id: 'usa-west-1',
    countryId: 'USA',
    name: 'Encourage Western Settlement',
    description: 'Promote migration into the western territories.',
    prerequisiteIds: ['usa-root'],
    durationTurns: 4,
    x: -1,
    y: 1,
    effect: { growthBonusDelta: 0.008, addTag: 'frontier_expansion' },
  },
  {
    id: 'usa-west-2',
    countryId: 'USA',
    name: 'Homestead Land Grants',
    description: 'Offer land grants to settlers willing to work the frontier.',
    prerequisiteIds: ['usa-west-1'],
    durationTurns: 4,
    x: -1,
    y: 2,
    effect: { stabilityDelta: 6, opinionDelta: 8 },
  },
  {
    id: 'usa-ind-1',
    countryId: 'USA',
    name: 'Railway Subsidies',
    description: 'Subsidize rail construction to knit the country together.',
    prerequisiteIds: ['usa-root'],
    durationTurns: 4,
    x: 1,
    y: 1,
    effect: { unlockTechId: 'railways', growthBonusDelta: 0.01 },
  },
  {
    id: 'usa-ind-2',
    countryId: 'USA',
    name: 'National Manufacturing Investment',
    description: 'Invest in domestic steel and manufacturing capacity.',
    prerequisiteIds: ['usa-ind-1'],
    durationTurns: 4,
    x: 1,
    y: 2,
    effect: { unlockTechId: 'steel_production', militaryBonusDelta: 10 },
  },
  {
    id: 'usa-bank-1',
    countryId: 'USA',
    name: 'National Bank Stability',
    description: "Stabilize the nation's finances through sound banking policy.",
    prerequisiteIds: ['usa-root'],
    durationTurns: 3,
    x: 0,
    y: 1,
    effect: { debtDelta: -25, stabilityDelta: 5 },
  },
  {
    id: 'usa-coast-to-coast',
    countryId: 'USA',
    name: 'Coast to Coast',
    description: 'Bring westward growth, industry, and sound finance together into a continental power.',
    prerequisiteIds: ['usa-west-2', 'usa-ind-2', 'usa-bank-1'],
    durationTurns: 6,
    x: 0,
    y: 3,
    effect: { stabilityDelta: 20, opinionDelta: 15, growthBonusDelta: 0.012 },
  },

  // ============ German Empire, 1914 — "Weltpolitik" ============
  {
    id: 'ger-root',
    countryId: 'GER',
    name: 'Reassert German Power',
    description: "Rally the Empire behind the Kaiser's ambitions.",
    prerequisiteIds: [],
    durationTurns: 3,
    x: 0,
    y: 0,
    effect: { stabilityDelta: 6, opinionDelta: 6 },
  },
  {
    id: 'ger-army-1',
    countryId: 'GER',
    name: 'Expand the General Staff',
    description: 'Grow the officer corps and planning apparatus of the Imperial Army.',
    prerequisiteIds: ['ger-root'],
    durationTurns: 4,
    x: -2,
    y: 1,
    effect: { militaryBonusDelta: 15 },
  },
  {
    id: 'ger-army-2',
    countryId: 'GER',
    name: 'Schlieffen Plan Revision',
    description: 'Refine the strategic plan for a two-front war.',
    prerequisiteIds: ['ger-army-1'],
    durationTurns: 5,
    x: -2,
    y: 2,
    effect: { unlockTechId: 'trench_warfare_logistics', militaryBonusDelta: 20 },
  },
  {
    id: 'ger-army-3',
    countryId: 'GER',
    name: 'Total Mobilization',
    description: 'Prepare the legal and logistical framework for mass conscription.',
    prerequisiteIds: ['ger-army-2'],
    durationTurns: 6,
    x: -2,
    y: 3,
    effect: { unlockTechId: 'mass_conscription_reform', militaryBonusDelta: 30 },
  },
  {
    id: 'ger-navy-1',
    countryId: 'GER',
    name: 'Risk Fleet Expansion',
    description: 'Build a battle fleet strong enough to deter the Royal Navy.',
    prerequisiteIds: ['ger-root'],
    durationTurns: 5,
    x: -1,
    y: 1,
    effect: { unlockTechId: 'dreadnought_construction', militaryBonusDelta: 20 },
  },
  {
    id: 'ger-navy-2',
    countryId: 'GER',
    name: 'U-Boat Doctrine',
    description: 'Develop submarine warfare doctrine to threaten enemy shipping.',
    prerequisiteIds: ['ger-navy-1'],
    durationTurns: 4,
    x: -1,
    y: 2,
    effect: { militaryBonusDelta: 15 },
  },
  {
    id: 'ger-ind-1',
    countryId: 'GER',
    name: 'Ruhr Industrial Investment',
    description: "Pour capital into the Ruhr valley's coal and steel works.",
    prerequisiteIds: ['ger-root'],
    durationTurns: 4,
    x: 1,
    y: 1,
    effect: { growthBonusDelta: 0.012 },
  },
  {
    id: 'ger-ind-2',
    countryId: 'GER',
    name: 'War Materiel Stockpiling',
    description: 'Shift industrial output toward stockpiling munitions and equipment.',
    prerequisiteIds: ['ger-ind-1'],
    durationTurns: 5,
    x: 1,
    y: 2,
    effect: { unlockTechId: 'total_war_industry', growthBonusDelta: 0.015 },
  },
  {
    id: 'ger-dip-1',
    countryId: 'GER',
    name: 'Strengthen the Triple Alliance',
    description: 'Deepen coordination with Vienna.',
    prerequisiteIds: ['ger-root'],
    durationTurns: 3,
    x: 0,
    y: 1,
    effect: { relationDelta: { targetId: 'AUH', delta: 20 } },
  },
  {
    id: 'ger-dip-2',
    countryId: 'GER',
    name: 'Guarantee Austria-Hungary',
    description: 'Formalize an unconditional guarantee of support to Vienna.',
    prerequisiteIds: ['ger-dip-1'],
    durationTurns: 4,
    x: 0,
    y: 2,
    effect: { formTreaty: { targetId: 'AUH', treaty: 'alliance' }, relationDelta: { targetId: 'AUH', delta: 15 } },
  },
  {
    id: 'ger-weltmacht',
    countryId: 'GER',
    name: 'Griff nach der Weltmacht',
    description: 'Bring army, navy, industry, and alliance together into a bid for world power.',
    prerequisiteIds: ['ger-army-3', 'ger-navy-2', 'ger-ind-2', 'ger-dip-2'],
    durationTurns: 6,
    x: -1,
    y: 4,
    effect: { stabilityDelta: 20, militaryBonusDelta: 25, opinionDelta: 10 },
  },

  // ============ Soviet Union, 1962 — "Premier's Gambit" ============
  {
    id: 'usr-root',
    countryId: 'USR',
    name: 'Consolidate the Presidium',
    description: "Cement the Premier's authority over the party apparatus.",
    prerequisiteIds: [],
    durationTurns: 3,
    x: 0,
    y: 0,
    effect: { stabilityDelta: 6, opinionDelta: 4 },
  },
  {
    id: 'usr-mil-1',
    countryId: 'USR',
    name: 'Expand the Red Army',
    description: 'Grow conventional forces along the western frontier.',
    prerequisiteIds: ['usr-root'],
    durationTurns: 4,
    x: -2,
    y: 1,
    effect: { militaryBonusDelta: 20 },
  },
  {
    id: 'usr-mil-2',
    countryId: 'USR',
    name: 'ICBM Crash Program',
    description: 'Race to field a credible intercontinental strike capability.',
    prerequisiteIds: ['usr-mil-1'],
    durationTurns: 6,
    x: -2,
    y: 2,
    effect: { unlockTechId: 'icbm_deployment', militaryBonusDelta: 30 },
  },
  {
    id: 'usr-mil-3',
    countryId: 'USR',
    name: 'Nuclear Triad',
    description: 'Complete the triad with a survivable submarine-based deterrent.',
    prerequisiteIds: ['usr-mil-2'],
    durationTurns: 6,
    x: -2,
    y: 3,
    effect: { unlockTechId: 'nuclear_submarine_fleet', militaryBonusDelta: 25 },
  },
  {
    id: 'usr-space-1',
    countryId: 'USR',
    name: 'Accelerate the Space Program',
    description: 'Pour resources into orbital launch capability.',
    prerequisiteIds: ['usr-root'],
    durationTurns: 5,
    x: -1,
    y: 1,
    effect: { unlockTechId: 'satellite_reconnaissance', opinionDelta: 10 },
  },
  {
    id: 'usr-space-2',
    countryId: 'USR',
    name: 'Cosmonaut Corps',
    description: 'Train a corps of cosmonauts for crewed spaceflight.',
    prerequisiteIds: ['usr-space-1'],
    durationTurns: 4,
    x: -1,
    y: 2,
    effect: { stabilityDelta: 8, opinionDelta: 10 },
  },
  {
    id: 'usr-ind-1',
    countryId: 'USR',
    name: 'Second Five-Year Plan',
    description: 'Set aggressive new industrial output targets.',
    prerequisiteIds: ['usr-root'],
    durationTurns: 4,
    x: 1,
    y: 1,
    effect: { growthBonusDelta: 0.012 },
  },
  {
    id: 'usr-ind-2',
    countryId: 'USR',
    name: 'Heavy Industry Focus',
    description: 'Prioritize heavy industry and electronics production.',
    prerequisiteIds: ['usr-ind-1'],
    durationTurns: 5,
    x: 1,
    y: 2,
    effect: { unlockTechId: 'transistor_electronics', growthBonusDelta: 0.014 },
  },
  {
    id: 'usr-dip-1',
    countryId: 'USR',
    name: 'Support Fraternal Socialist States',
    description: 'Deepen material support for allied socialist governments.',
    prerequisiteIds: ['usr-root'],
    durationTurns: 3,
    x: 0,
    y: 1,
    effect: { relationDelta: { targetId: 'CUB', delta: 20 } },
  },
  {
    id: 'usr-dip-2',
    countryId: 'USR',
    name: 'Export Revolution',
    description: 'Court non-aligned states with material and ideological support.',
    prerequisiteIds: ['usr-dip-1'],
    durationTurns: 5,
    x: 0,
    y: 2,
    effect: { relationDelta: { targetId: 'IND', delta: 15 } },
  },
  {
    id: 'usr-peak-power',
    countryId: 'USR',
    name: 'Peak of Soviet Power',
    description: 'Bring military, scientific, industrial, and diplomatic strength together at their height.',
    prerequisiteIds: ['usr-mil-3', 'usr-space-2', 'usr-ind-2', 'usr-dip-2'],
    durationTurns: 6,
    x: -1,
    y: 4,
    effect: { stabilityDelta: 20, militaryBonusDelta: 25, opinionDelta: 15 },
  },
];

export const FOCUS_REGISTRY: Record<FocusId, FocusDef> = Object.fromEntries(registry.map((f) => [f.id, f]));

/** All focuses belonging to one country's tree, in authoring order. */
export function focusesForCountry(countryId: string): FocusDef[] {
  return registry.filter((f) => f.countryId === countryId);
}
